<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-11 at 02:38:04.
 */
include '../../../Libraries/Class/VO/BaseVO.php';
class BaseVOTest extends PHPUnit_Framework_TestCase {

    /**
     * @var BaseVO
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BaseVO;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }

    /**
     * @covers BaseVO::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        $this->object->setId(666);
        $this->assertEquals(666, $this->object->getId());
    }

    /**
     * @covers BaseVO::setId
     * @todo   Implement testSetId().
     */
    public function testSetId() {
        $this->object->setId(666);
        $this->assertEquals(666, $this->object->getId());
    }

    /**
     * @covers BaseVO::getReferencia
     * @todo   Implement testGetReferencia().
     */
    public function testGetReferencia() {
        $this->object->setReferencia('ExampleRef-121212');
        $this->assertEquals('ExampleRef-121212', $this->object->getReferencia());
    }

    /**
     * @covers BaseVO::setReferencia
     * @todo   Implement testSetReferencia().
     */
    public function testSetReferencia() {
        $this->object->setReferencia('ExampleRef-121212');
        $this->assertEquals('ExampleRef-121212', $this->object->getReferencia());
    }

}
